language: php

php:
  - 7.0
  - 7.1

env:
  - DB=mysql

# For easy compatibility with docker env.
addons:
  hosts:
    - mysql

before_script:
  - composer global require "fxp/composer-asset-plugin"
  - composer install --prefer-source --no-interaction --dev

  - mysql -e 'CREATE DATABASE test;'
