version: '2'

services:
  php:
    build: .
    volumes:
      - "./:/var/www"
      - "~/.composer/cache:/root/.composer/cache"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
